shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  main:
    requires: [~commit]
  component:
    requires: []
  
  native-remote-join-test-succeed:
    requires: 
      - sd@2:component2
      - sd@1:component1
      
  native-remote-join-test-fail:
    requires: 
      - sd@2:component-fail2
      - sd@1:component1
