shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  main:
    requires: [~commit]
  component:
    requires: [~commit]
  
  native-remote-join-test-succeed:
    requires: [sd@3:component2, sd@2:component1]
    #requires: [~commit]
      
  native-remote-join-test-fail:
    requires: [sd@3:component-fail2, sd@2:component1]
    #requires: [~commit]
