shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  component:
    requires: []
  
  native-remote-join-test-succeed:
    requires: 
      - sd@52:component
      - sd@53:component
      
  native-remote-join-test-fail:
    requires: 
      - sd@52:component-fail
      - sd@53:component
